<a href="https://colab.research.google.com/github/nys726/first/blob/master/%EB%85%B8%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Repeat 노드

In [0]:
import numpy as np
D, N = 8, 7
x = np.random.randn(1, D)                # 입력
y = np.repeat(x, N, axis=0)              # 순전파
dy = np.random.randn(N, D)               # 무작위 기울기
dx = np.sum(dy, axis=0, keepdims=True)   # 역전파

In [0]:
x,y

(array([[-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841]]),
 array([[-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841],
        [-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841],
        [-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841],
        [-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841],
        [-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841],
        [-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841],
        [-0.90048531, -0.43072424,  2.15515792,  0.43138393, -1.60884386,
         -0.31347969,  0.5409478 , -1.48304841]]))

In [0]:
dy

array([[ 1.41992128,  1.53022047,  0.60306473,  1.4941058 , -1.72081855,
         1.18674846, -1.52461593, -0.1651855 ],
       [-0.81204935,  0.56041012, -1.70631297, -0.89922355,  0.29497896,
         1.50660683,  0.20384347,  1.06611141],
       [ 0.69893708, -2.03314221,  0.81820963, -1.60308986,  1.05126253,
         0.94802621,  0.49605536, -1.67906077],
       [ 1.27650995,  0.06979146, -0.36242733, -1.33227509,  0.56693247,
         0.85044573, -0.26758678,  0.47595615],
       [-0.22414036,  0.0791642 ,  2.08047708,  0.59612173, -0.70847024,
        -0.25875781,  2.10329911,  2.67880303],
       [ 0.21104421,  0.47712771, -1.42540495, -0.22344168, -0.70568343,
         0.52209442, -0.025093  ,  0.43178397],
       [-1.07146832,  0.14053737, -0.33474495, -0.62647712, -0.46524155,
         0.38968352, -1.1423852 ,  1.64998636]])

In [0]:
dx

array([[ 1.49875448,  0.82410913, -0.32713877, -2.59427977, -1.6870398 ,
         5.14484735, -0.15648296,  4.45839465]])

##Sum 노드

In [0]:
import numpy as np
D, N = 8, 7
x = np.random.randn(N, D)             # 입력
y = np.sum(x, axis=0, keepdims=True)  # 순전파
dy = np.random.randn(1, D)            # 무작위 기울기
dx = np.repeat(dy, N, axis = 0)       # 역전파

## MatMul 노드

In [0]:
class MatMul:
  def __init__(self, W):
    self.params = [W]
    self.grads = [np.zeros_like(W)]
    self.x = None

  def forword(self, x):
    W, = self.params
    out = np.matmul(x, W)
    self.x = x
    return
    
  def backward(self, dout):
    W, = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    self.grads[0][...]=dW
    return dx

## Sigmoid 계층

In [0]:
class MatMul:
  def __init__(self):
    self.params, self.grads = [], []
    self.out = None

  def forword(self, x):
    out = 1 / (1+np.exp(-x))
    self.out = out
    return out
    
  def backward(self, dout):
    dx = dout * (1.0 - self.out) * self.out
    return dx

##Affine계층

In [0]:
class MatMul:
  def __init__(self, W, b):
    self.params = [W, b]
    self.grads = [np.zeros_like(W), np.zeros_like(b)]
    self.x = None

  def forword(self, x):
    W, b = self.params
    out = np.matmul(x, W) +b
    self.x = x
    return
    
  def backward(self, dout):
    W, b = self.params
    dx = np.matmul(dout, W.T)
    dW = np.matmul(self.x.T, dout)
    db = np.sum(dout, axis=0)
    self.grads[0][...]=dW
    self.grads[1][...]=db
    return dx